import { TechProps } from '@/types/tech';

export const TECH: TechProps[] = [
  { icon: 'logos:javascript', title: 'JavaScript' },
  { icon: 'logos:typescript-icon', title: 'TypeScript' },
  { icon: 'vscode-icons:file-type-html', title: 'HTML' },
  { icon: 'vscode-icons:file-type-css', title: 'CSS' },
  { icon: 'vscode-icons:file-type-sass', title: 'SASS' },
  { icon: 'logos:vitejs', title: 'Vite' },
  { icon: 'logos:webpack', title: 'Webpack' },
  { icon: 'logos:eslint', title: 'ESLint' },
  { icon: 'logos:prettier', title: 'Prettier' },
  { icon: 'logos:react', title: 'React.js' },
  { icon: 'simple-icons:nextdotjs', title: 'Next.js' },
  { icon: 'logos:tailwindcss-icon', title: 'TailwindCSS' },
  { icon: 'logos:effector', title: 'Effector' },
  { icon: 'logos:docker-icon', title: 'Docker' },
  { icon: 'logos:jest', title: 'Jest' },
  { icon: 'logos:playwright', title: 'Playwright' },
  { icon: 'logos:nodejs-icon', title: 'Node.js' },
  { icon: 'skill-icons:expressjs-light', title: 'Express' },
  { icon: 'skill-icons:prisma', title: 'Prisma' },
  { icon: 'logos:postgresql', title: 'PostgreSQL' },
  { icon: 'logos:git-icon', title: 'Git' },
  { icon: 'logos:npm-2', title: 'Npm' },
  { icon: 'logos:figma', title: 'Figma' },
];
